/**
 * Pre-trained main-chart AI weights — AUTO-GENERATED by agent-training.test.ts, do not edit.
 *
 * Trained on 1913 causal BTC-USD forecasts (Coinbase spot):
 * 1D trailing year, 1h Nov-2024 election rally, recent 1h / 15m / 5m / 1m.
 * Fresh installs start here via pretrainedAgentLearningState(); live outcomes
 * keep adapting every cell from this prior. Regenerates byte-identically on
 * every test run unless the engine, data, or harness changed.
 */
import type { AgentLearningState } from './market-agents'

export const AGENT_PRETRAINED_LEARNING: AgentLearningState = {
  "version": 1,
  "updatedAt": "2026-09-10T00:00:00.000Z",
  "agents": {
    "regime": {
      "overall": {
        "skill": 0.8722,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.8152,
          "samples": 700
        },
        "range": {
          "skill": 0.8463,
          "samples": 936
        },
        "breakout": {
          "skill": 0.5854,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.5386,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.6793,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.6714,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6674,
          "samples": 284
        },
        "1h": {
          "skill": 0.6311,
          "samples": 501
        },
        "15m": {
          "skill": 0.7616,
          "samples": 279
        },
        "5m": {
          "skill": 0.8136,
          "samples": 279
        },
        "1m": {
          "skill": 0.8722,
          "samples": 509
        }
      }
    },
    "trend": {
      "overall": {
        "skill": 0.7255,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.6489,
          "samples": 700
        },
        "range": {
          "skill": 0.7287,
          "samples": 936
        },
        "breakout": {
          "skill": 0.6197,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.6335,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.6758,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.6504,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6486,
          "samples": 284
        },
        "1h": {
          "skill": 0.6222,
          "samples": 501
        },
        "15m": {
          "skill": 0.6804,
          "samples": 279
        },
        "5m": {
          "skill": 0.7622,
          "samples": 279
        },
        "1m": {
          "skill": 0.7255,
          "samples": 509
        }
      }
    },
    "momentum": {
      "overall": {
        "skill": 0.7826,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.6802,
          "samples": 700
        },
        "range": {
          "skill": 0.7955,
          "samples": 936
        },
        "breakout": {
          "skill": 0.5888,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.5497,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.6631,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.6863,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6448,
          "samples": 284
        },
        "1h": {
          "skill": 0.6313,
          "samples": 501
        },
        "15m": {
          "skill": 0.7481,
          "samples": 279
        },
        "5m": {
          "skill": 0.7558,
          "samples": 279
        },
        "1m": {
          "skill": 0.7826,
          "samples": 509
        }
      }
    },
    "macd": {
      "overall": {
        "skill": 0.8333,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.7472,
          "samples": 700
        },
        "range": {
          "skill": 0.8264,
          "samples": 936
        },
        "breakout": {
          "skill": 0.6179,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.6341,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.7297,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.718,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6498,
          "samples": 284
        },
        "1h": {
          "skill": 0.6293,
          "samples": 501
        },
        "15m": {
          "skill": 0.7463,
          "samples": 279
        },
        "5m": {
          "skill": 0.7875,
          "samples": 279
        },
        "1m": {
          "skill": 0.8333,
          "samples": 509
        }
      }
    },
    "level-strength": {
      "overall": {
        "skill": 0.8448,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.7635,
          "samples": 700
        },
        "range": {
          "skill": 0.8148,
          "samples": 936
        },
        "breakout": {
          "skill": 0.6981,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.7369,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.7247,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.7412,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.669,
          "samples": 284
        },
        "1h": {
          "skill": 0.6964,
          "samples": 501
        },
        "15m": {
          "skill": 0.7143,
          "samples": 279
        },
        "5m": {
          "skill": 0.8055,
          "samples": 279
        },
        "1m": {
          "skill": 0.8448,
          "samples": 509
        }
      }
    },
    "structure": {
      "overall": {
        "skill": 0.7616,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.7085,
          "samples": 700
        },
        "range": {
          "skill": 0.7424,
          "samples": 936
        },
        "breakout": {
          "skill": 0.6666,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.712,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.6483,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.6618,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.7017,
          "samples": 284
        },
        "1h": {
          "skill": 0.7413,
          "samples": 501
        },
        "15m": {
          "skill": 0.6734,
          "samples": 279
        },
        "5m": {
          "skill": 0.7298,
          "samples": 279
        },
        "1m": {
          "skill": 0.7616,
          "samples": 509
        }
      }
    },
    "ensemble": {
      "overall": {
        "skill": 0.8458,
        "samples": 1852
      },
      "byRegime": {
        "chop": {
          "skill": 0.7729,
          "samples": 700
        },
        "range": {
          "skill": 0.8273,
          "samples": 936
        },
        "breakout": {
          "skill": 0.6392,
          "samples": 54
        },
        "breakdown": {
          "skill": 0.6473,
          "samples": 32
        },
        "trend-down": {
          "skill": 0.7114,
          "samples": 27
        },
        "trend-up": {
          "skill": 0.7212,
          "samples": 103
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6607,
          "samples": 284
        },
        "1h": {
          "skill": 0.6568,
          "samples": 501
        },
        "15m": {
          "skill": 0.7506,
          "samples": 279
        },
        "5m": {
          "skill": 0.7861,
          "samples": 279
        },
        "1m": {
          "skill": 0.8458,
          "samples": 509
        }
      }
    },
    "context": {
      "overall": {
        "skill": 0.8051,
        "samples": 1317
      },
      "byRegime": {
        "chop": {
          "skill": 0.7109,
          "samples": 502
        },
        "range": {
          "skill": 0.7995,
          "samples": 632
        },
        "breakdown": {
          "skill": 0.7975,
          "samples": 20
        },
        "trend-down": {
          "skill": 0.6788,
          "samples": 20
        },
        "breakout": {
          "skill": 0.6784,
          "samples": 41
        },
        "trend-up": {
          "skill": 0.7573,
          "samples": 102
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.6479,
          "samples": 135
        },
        "1h": {
          "skill": 0.594,
          "samples": 381
        },
        "15m": {
          "skill": 0.7717,
          "samples": 221
        },
        "5m": {
          "skill": 0.7593,
          "samples": 250
        },
        "1m": {
          "skill": 0.8051,
          "samples": 330
        }
      }
    }
  }
}
