/**
 * Pre-trained MACD AI weights — AUTO-GENERATED by macd-training.test.ts, do not edit.
 *
 * Trained on 1334 causal BTC-USD forecasts (Coinbase spot):
 * 1D trailing year, 1h Nov-2024 election rally, recent 1h / 15m / 5m.
 * Fresh installs start here via pretrainedMacdAiLearningState(); live outcomes
 * keep adapting every cell from this prior. Regenerates byte-identically on
 * every test run unless the engine, data, or harness changed.
 */
import type { MacdAiLearningState } from './macd-forecast'

export const MACD_PRETRAINED_LEARNING: MacdAiLearningState = {
  "version": 1,
  "updatedAt": "2026-09-10T00:00:00.000Z",
  "agents": {
    "cross-timer": {
      "overall": {
        "skill": 0.403,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.4948,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.3671,
          "samples": 200
        },
        "diverging": {
          "skill": 0.3653,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.8164,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.4736,
          "samples": 279
        },
        "1h": {
          "skill": 0.4811,
          "samples": 497
        },
        "15m": {
          "skill": 0.4185,
          "samples": 279
        },
        "5m": {
          "skill": 0.403,
          "samples": 279
        }
      }
    },
    "zero-scout": {
      "overall": {
        "skill": 0.5639,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5784,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.4302,
          "samples": 200
        },
        "diverging": {
          "skill": 0.5995,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.491,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5351,
          "samples": 279
        },
        "1h": {
          "skill": 0.4252,
          "samples": 497
        },
        "15m": {
          "skill": 0.6122,
          "samples": 279
        },
        "5m": {
          "skill": 0.5639,
          "samples": 279
        }
      }
    },
    "touch-judge": {
      "overall": {
        "skill": 0.5233,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5621,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.5299,
          "samples": 200
        },
        "diverging": {
          "skill": 0.5464,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.7982,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.4841,
          "samples": 279
        },
        "1h": {
          "skill": 0.488,
          "samples": 497
        },
        "15m": {
          "skill": 0.4699,
          "samples": 279
        },
        "5m": {
          "skill": 0.5233,
          "samples": 279
        }
      }
    },
    "thrust-reader": {
      "overall": {
        "skill": 0.8343,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.7534,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.5757,
          "samples": 200
        },
        "diverging": {
          "skill": 0.7655,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.8089,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.8009,
          "samples": 279
        },
        "1h": {
          "skill": 0.5467,
          "samples": 497
        },
        "15m": {
          "skill": 0.7441,
          "samples": 279
        },
        "5m": {
          "skill": 0.8343,
          "samples": 279
        }
      }
    },
    "memory": {
      "overall": {
        "skill": 0.5811,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5972,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.4757,
          "samples": 200
        },
        "diverging": {
          "skill": 0.5692,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.7286,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5735,
          "samples": 279
        },
        "1h": {
          "skill": 0.4852,
          "samples": 497
        },
        "15m": {
          "skill": 0.5612,
          "samples": 279
        },
        "5m": {
          "skill": 0.5811,
          "samples": 279
        }
      }
    },
    "ensemble": {
      "overall": {
        "skill": 0.5811,
        "samples": 1334
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5972,
          "samples": 303
        },
        "fresh-cross": {
          "skill": 0.4757,
          "samples": 200
        },
        "diverging": {
          "skill": 0.5692,
          "samples": 644
        },
        "touch-zone": {
          "skill": 0.7286,
          "samples": 187
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5735,
          "samples": 279
        },
        "1h": {
          "skill": 0.4852,
          "samples": 497
        },
        "15m": {
          "skill": 0.5612,
          "samples": 279
        },
        "5m": {
          "skill": 0.5811,
          "samples": 279
        }
      }
    }
  },
  "calibration": {
    "crossBarsBias": 0.205,
    "zeroBarsBias": 1.7222,
    "samples": 585
  }
}
