/**
 * Pre-trained MACD AI weights — AUTO-GENERATED by macd-training.test.ts, do not edit.
 *
 * Trained on 1843 causal BTC-USD forecasts (Coinbase spot):
 * 1D trailing year, 1h Nov-2024 election rally, recent 1h / 15m / 5m.
 * Fresh installs start here via pretrainedMacdAiLearningState(); live outcomes
 * keep adapting every cell from this prior. Regenerates byte-identically on
 * every test run unless the engine, data, or harness changed.
 */
import type { MacdAiLearningState } from './macd-forecast'

export const MACD_PRETRAINED_LEARNING: MacdAiLearningState = {
  "version": 1,
  "updatedAt": "2026-09-10T00:00:00.000Z",
  "agents": {
    "cross-timer": {
      "overall": {
        "skill": 0.4647,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5728,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.421,
          "samples": 298
        },
        "diverging": {
          "skill": 0.2517,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.7231,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.467,
          "samples": 279
        },
        "1h": {
          "skill": 0.4948,
          "samples": 497
        },
        "15m": {
          "skill": 0.4763,
          "samples": 279
        },
        "5m": {
          "skill": 0.3836,
          "samples": 279
        },
        "1m": {
          "skill": 0.4647,
          "samples": 509
        }
      }
    },
    "zero-scout": {
      "overall": {
        "skill": 0.4839,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.4928,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.4392,
          "samples": 298
        },
        "diverging": {
          "skill": 0.5657,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.4878,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5351,
          "samples": 279
        },
        "1h": {
          "skill": 0.4252,
          "samples": 497
        },
        "15m": {
          "skill": 0.6122,
          "samples": 279
        },
        "5m": {
          "skill": 0.5639,
          "samples": 279
        },
        "1m": {
          "skill": 0.4839,
          "samples": 509
        }
      }
    },
    "touch-judge": {
      "overall": {
        "skill": 0.6371,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.4572,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.6187,
          "samples": 298
        },
        "diverging": {
          "skill": 0.5054,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.8532,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5598,
          "samples": 279
        },
        "1h": {
          "skill": 0.5471,
          "samples": 497
        },
        "15m": {
          "skill": 0.6855,
          "samples": 279
        },
        "5m": {
          "skill": 0.664,
          "samples": 279
        },
        "1m": {
          "skill": 0.6371,
          "samples": 509
        }
      }
    },
    "thrust-reader": {
      "overall": {
        "skill": 0.7605,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.7674,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.5891,
          "samples": 298
        },
        "diverging": {
          "skill": 0.636,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.898,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.8009,
          "samples": 279
        },
        "1h": {
          "skill": 0.5467,
          "samples": 497
        },
        "15m": {
          "skill": 0.6929,
          "samples": 279
        },
        "5m": {
          "skill": 0.8608,
          "samples": 279
        },
        "1m": {
          "skill": 0.7605,
          "samples": 509
        }
      }
    },
    "memory": {
      "overall": {
        "skill": 0.5866,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5726,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.517,
          "samples": 298
        },
        "diverging": {
          "skill": 0.4897,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.7405,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5907,
          "samples": 279
        },
        "1h": {
          "skill": 0.5034,
          "samples": 497
        },
        "15m": {
          "skill": 0.6167,
          "samples": 279
        },
        "5m": {
          "skill": 0.6181,
          "samples": 279
        },
        "1m": {
          "skill": 0.5866,
          "samples": 509
        }
      }
    },
    "ensemble": {
      "overall": {
        "skill": 0.5866,
        "samples": 1843
      },
      "byRegime": {
        "approaching-cross": {
          "skill": 0.5726,
          "samples": 433
        },
        "fresh-cross": {
          "skill": 0.517,
          "samples": 298
        },
        "diverging": {
          "skill": 0.4897,
          "samples": 857
        },
        "touch-zone": {
          "skill": 0.7405,
          "samples": 255
        }
      },
      "byTimeframe": {
        "1D": {
          "skill": 0.5907,
          "samples": 279
        },
        "1h": {
          "skill": 0.5034,
          "samples": 497
        },
        "15m": {
          "skill": 0.6167,
          "samples": 279
        },
        "5m": {
          "skill": 0.6181,
          "samples": 279
        },
        "1m": {
          "skill": 0.5866,
          "samples": 509
        }
      }
    }
  },
  "calibration": {
    "crossBarsBias": 1.2192,
    "zeroBarsBias": -1.2548,
    "samples": 781,
    "byTimeframe": {
      "1D": {
        "crossBarsBias": 0.1557,
        "zeroBarsBias": 0.3148,
        "samples": 112
      },
      "1h": {
        "crossBarsBias": 0.9148,
        "zeroBarsBias": -2.1202,
        "samples": 217
      },
      "15m": {
        "crossBarsBias": 0.1146,
        "zeroBarsBias": -0.7807,
        "samples": 122
      },
      "5m": {
        "crossBarsBias": 0.2876,
        "zeroBarsBias": 1.7396,
        "samples": 121
      },
      "1m": {
        "crossBarsBias": 1.2192,
        "zeroBarsBias": -1.3249,
        "samples": 209
      }
    }
  }
}
